# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork
  mainnet-fork:
    explorer: https://api.etherscan.io/api
    cmd: ganache-cli
    cmd_settings:
      accounts: 50
      mnemonic: brownie
      fork: https://eth-mainnet.alchemyapi.io/v2/$ALCHEMYAPI_TOKEN
      default_balance: 500 ether
      chain_id: 1

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.6.12

reports:
